CREATE TABLE "main"."CARPART" (
ID  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
ENGINE  INTEGER NOT NULL DEFAULT 100,
BRAKES  INTEGER NOT NULL DEFAULT 100,
TYRES  INTEGER NOT NULL DEFAULT 100,
SUSPENTION  INTEGER NOT NULL DEFAULT 100,
TURBO	INTEGER NOT NULL DEFAULT 100,
UNIQUE (ID)
);

ALTER TABLE CARPART ADD COLUMN USERCAR_ID INTEGER REFERENCES USERCAR(ID) ON DELETE CASCADE ON UPDATE CASCADE;
