CREATE TABLE "main"."USER" ( 
"ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"LOGIN" TEXT(50) NOT NULL,
"PASSWORD" TEXT(50) NOT NULL,
"COINS" INTEGER NOT NULL DEFAULT 100,
UNIQUE ("ID"), UNIQUE ("LOGIN") )