CREATE TABLE "main"."USERCAR" (
"ID"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"NAME"  TEXT NOT NULL,
"ACCELERATION"  INTEGER NOT NULL,
"HANDLING"  INTEGER NOT NULL,
"BREAKING"  INTEGER NOT NULL,
"TOPSPEED"  INTEGER NOT NULL,
"USER_ID"	INTEGER,
FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID") ON DELETE CASCADE ON UPDATE CASCADE,
UNIQUE ("ID"),
UNIQUE ("NAME")
);