CREATE TABLE "main"."CARPART" (
ID  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
ENGINE  INTEGER NOT NULL DEFAULT 100,
BRAKES  INTEGER NOT NULL DEFAULT 100,
TYRES  INTEGER NOT NULL DEFAULT 100,
SUSPENTION  INTEGER NOT NULL DEFAULT 100,
TURBO	INTEGER NOT NULL DEFAULT 100,
UNIQUE (ID)
);

ALTER TABLE USERCAR ADD COLUMN CARPART_ID INTEGER REFERENCES CARPART(ID) ON DELETE CASCADE ON UPDATE CASCADE;
