CREATE TABLE "main"."CAR" (
"ID"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"NAME"  TEXT NOT NULL,
"ACCELERATION"  INTEGER NOT NULL,
"HANDLING"  INTEGER NOT NULL,
"BRAKING"  INTEGER NOT NULL,
"TOPSPEED"  INTEGER NOT NULL,
UNIQUE ("ID"),
UNIQUE ("NAME")
)
