
INSERT INTO USER (ID, LOGIN, PASSWORD, COINS) VALUES 
(1, 'MaciekxD', '123xD', 300);


INSERT INTO USERCAR (ID, NAME, ACCELERATION, HANDLING, BREAKING, TOPSPEED, USER_ID, CARPART_ID) values
(1, 'ferrari', 60, 65, 80, 40, 1, null);